name       : python-gnupg
version    : 0.5.0
release    : 4
source     :
    - https://pypi.io/packages/source/p/python-gnupg/python-gnupg-0.5.0.tar.gz : 70758e387fc0e0c4badbcb394f61acbe68b34970a8fed7e0f7c89469fe17912a
homepage   : https://github.com/vsajip/python-gnupg
license    : BSD-3-Clause
component  : programming.python
summary    : A wrapper for the Gnu Privacy Guard (GPG or GnuPG)
description: |
    python-gnupg allows easy access to GnuPG’s key management, encryption and signature functionality from Python programs.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - gnupg
build      : |
    %python3_setup
install    : |
    %python3_install
