name       : python-gnupg
version    : 0.4.7
release    : 3
source     :
    - https://pypi.io/packages/source/p/python-gnupg/python-gnupg-0.4.7.tar.gz : 2061f56b1942c29b92727bf9aecbd3cea3893acc9cccbdc7eb4604285efe4ac7
license    : BSD-3-Clause
component  : programming.python
summary    : Python library for GnuPG key management, encryption and signature
description: |
    python-gnupg allows easy access to GnuPG’s key management, encryption and signature functionality from Python programs.
rundeps    :
    - gnupg
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
